### ISSUE TITLE
[Sentence Embedding] ELMO doesn't take weight

### ISSUE THREAD

**Issue by dsleo** [dataiku/dataiku-contrib#101]
As of [this](https://github.com/dataiku/dataiku-contrib/blob/master/sentence-embedding/python-lib/sentence_embedding_utils.py#L226-230), ELMO doesn't take weights. Not sure if intended @RedaAffane ?  
Also there is a missing `else` in [here](https://github.com/dataiku/dataiku-contrib/blob/master/sentence-embedding/python-lib/sentence_embedding_utils.py#L232)

**Comment by RedaAffane** [comment]
It does take weights. But since the ELMO function takes batches rather than single observations, I changed the paradigm a bit: The weights are computed in the function _get_elmo_text_batches_sif_, and integrated into the embeddings in the function _elmo_weighted_average_embedding_

**Comment by du-phan** [comment]
This will be part of the fix in the #104
