### ISSUE TITLE
Using Forecast Application with Partitions

### ISSUE THREAD

**Issue by QingyuKathyXu** [dataiku/dataiku-contrib#133]
Hello, I am facing errors while trying to use partitions in conjunction with the forecast application. I created a partition based on the year-month and added discrete variables so the structure looks something like: "YYYY-MM|var1_var2_var3". I tried running the forecast application with the partition identifier and obtain an error for "Invalid partition identifier, has 2 dimensions, expected 1", how can I properly use the partitions with the forecast application?

**Comment by alexcombessie** [comment]
Hello, the plugin currently supports only one discrete partition. If you remove the date partitioning and keep only one discrete dimension, the plugin recipe will train forecasting models separately for each partition. If you have multiple columns to identify a partition, you can concatenate them into a single column, and then partition by this column. You can find more details at the end of the official plugin page: https://www.dataiku.com/dss/plugins/info/forecast.html

**Comment by QingyuKathyXu** [comment]
Hello Alex, thanks for the reply, I have created a single column to partition by as suggested. First I tested by running the "Cleaning" portion of the Forecast application node on 2 specific partitions. The test succeeded so I went on to add the rest of my partitions by adding each unique partition separated by commas (,). When I run the node, I receive a Job processes died (killed - maybe out of memory?) error. I wanted to know:

1. Is it possible to automatically run the forecasting node for each unique partition without having to manually input the partitions and separating by commas (,)?
2. Is there a limit to how many partitions can be input at a time for the node to run?

Thanks,
Kathy

**Comment by alexcombessie** [comment]
Hi, to run a recipe on each unique partition you will need to compute the full list of partitions in comma or / separated format. You can automate that using project variables. For your second question, you can do that for each recipe in the advanced tab under the limit number of activities. Hope that helps, Alex

**Comment by QingyuKathyXu** [comment]
Hello Alex, thanks so much for providing the sample project!

I uploaded the project into a production level DSS instance to test out. While testing I found that the global variables did not behave the way I expected to while running the forecast (cleaning), and split visual recipes. For the prepare recipe I was able to use the global variable name: "store_department_combinations" in the Recipe Run Options where it asks to "Please define partition(s) to build". However, when I try to do the same in the forecast (cleaning), and split visual recipes I get an error and have to use the full list of partitions in / separated format for the recipe to work. If I use the name of the global variable I get the following error: " Path does not exist
Error while connecting to dataset PROJECTNAME.walmart_sales_partitioned (partition store_department_combinations), caused by: DataStoreIOException: Path does not exist in the dataset walmart_sales_partitioned: '/store_department_combinations/'", do you have any insight into why this occurs?

Best,
Kathy

**Comment by alexcombessie** [comment]
Hi,
 If you run recipe from the flow, you will need to manually copy the variable value in the recipe partition settings, for instance:
"24_40/24_4/24_38/24_37/24_36/24_35/24_34/24_33/24_32/24_31/24_30/24_3/24_29/24_28/24_27/24_26/24_25/24_24/24_23/24_22/24_21/24_20/24_2/24_19/24_17/24_16/24_14/24_13/24_12/24_11/24_10/24_1/23_97/23_96/23_95/23_93/23_92/23_91/23_90/23_9/23_87/23_85/23_83/23_82/23_81/23_8/23_79/23_74/23_72/23_71/23_7/23_67/23_6/23_59/23_56/23_55/23_54/23_52/23_50/23_5/23_49/23_46/23_44/23_42/23_41/23_40/23_4/23_38/23_36/23_35/23_34/23_33/23_32/23_31/23_30/23_3/23_29/23_28/23_27/23_26/23_25/23_24/23_23/23_22/23_21/23_20/23_2/23_19/23_17/23_16/23_14/23_13/23_12/23_11/23_10/23_1/22_97/22_95/22_93/22_92/22_91/22_90/22_9/22_87/22_85/22_83/22_82/22_81/22_80/22_8/22_79/22_74/22_72/22_71/22_7/22_67/22_60/22_6/22_59/22_58/22_56/22_55/22_54/22_52/22_5/22_46/22_44/22_42/22_41/22_40/22_4/22_38/22_36/22_35/22_34/22_33/22_32/22_31/22_30/22_3/22_29/22_28/22_27/22_26/22_25/22_24/22_23/22_22/22_21/22_20/22_2/22_17/22_16/22_14/22_13/22_12/22_11/22_10/22_1/21_97/21_95/21_93/21_92/21_91/21_90/21_9/21_87/21_85/21_83/21_82/21_81/21_8/21_79/21_74/21_72/21_71/21_7/21_67/21_6/21_59/21_56/21_55/21_52/21_5/21_49/21_46/21_44/21_42/21_41/21_40/21_4/21_38/21_36/21_35/21_34/21_33/21_32/21_31/21_30/21_3/21_29/21_28/21_27/21_26/21_25/21_24/21_23/21_22/21_21/21_20/21_2/21_19/21_17/21_16/21_14/21_13/21_12/21_11/21_10/21_1/20_98/20_97/20_95/20_94/20_93/20_92/20_91/20_90/20_9/20_87/20_85/20_83/20_82/20_81/20_80/20_8/20_79/20_74/20_72/20_71/20_7/20_67/20_60/20_6/20_59/20_58/20_56/20_55/20_54/20_52/20_50/20_5/20_49/20_46/20_44/20_42/20_41/20_40/20_4/20_38/20_37/20_36/20_35/20_34/20_33/20_32/20_31/20_30/20_3/20_29/20_28/20_27/20_26/20_25/20_24/20_23/20_22/20_21/20_20/20_2/20_17/20_16/20_14/20_13/20_12/20_11/20_10/20_1/1_98/1_97/1_95/1_94/1_93/1_92/1_91/1_90/1_9/1_87/1_85/1_83/1_82/1_81/1_80/1_8/1_79/1_74/1_72/1_71/1_7/1_67/1_60/1_6/1_59/1_58/1_56/1_55/1_52/1_5/1_49/1_46/1_44/1_42/1_41/1_40/1_4/1_38/1_37/1_36/1_35/1_34/1_33/1_32/1_31/1_30/1_3/1_29/1_28/1_27/1_26/1_25/1_24/1_23/1_22/1_21/1_20/1_2/1_19/1_17/1_16/1_14/1_13/1_12/1_11/1_10/1_1/19_98/19_97/19_96/19_95/19_94/19_93/19_92/19_91/19_90/19_9/19_87/19_85/19_83/19_82/19_81/19_80/19_8/19_79/19_74/19_72/19_71/19_7/19_67/19_60/19_6/19_59/19_58/19_56/19_55/19_52/19_50/19_5/19_49/19_46/19_44/19_42/19_41/19_40/19_4/19_38/19_37/19_36/19_35/19_34/19_33/19_32/19_31/19_30/19_3/19_29/19_28/19_27/19_26/19_25/19_24/19_23/19_22/19_21/19_20/19_2/19_17/19_16/19_14/19_13/19_12/19_11/19_10/19_1/18_95/18_92/18_91/18_90/18_9/18_87/18_85/18_82/18_81/18_8/18_79/18_74/18_72/18_71/18_7/18_67/18_6/18_59/18_58/18_56/18_55/18_52/18_5/18_49/18_46/18_44/18_42/18_41/18_40/18_4/18_38/18_36/18_35/18_34/18_33/18_32/18_31/18_30/18_3/18_29/18_28/18_27/18_26/18_25/18_24/18_23/18_22/18_21/18_20/18_2/18_19/18_17/18_16/18_14/18_13/18_12/18_11/18_10/18_1/17_97/17_95/17_93/17_92/17_91/17_90/17_9/17_87/17_85/17_83/17_82/17_81/17_80/17_8/17_79/17_74/17_72/17_71/17_7/17_67/17_60/17_6/17_59/17_58/17_56/17_55/17_52/17_5/17_48/17_46/17_44/17_42/17_40/17_4/17_38/17_36/17_35/17_34/17_33/17_32/17_31/17_30/17_3/17_29/17_28/17_27/17_26/17_25/17_24/17_23/17_22/17_21/17_20/17_2/17_19/17_17/17_16/17_14/17_13/17_12/17_11/17_10/17_1/16_97/16_96/16_95/16_92/16_91/16_90/16_9/16_87/16_85/16_82/16_81/16_8/16_79/16_74/16_72/16_71/16_7/16_67/16_6/16_56/16_55/16_52/16_5/16_46/16_44/16_42/16_41/16_40/16_4/16_38/16_36/16_35/16_34/16_33/16_32/16_31/16_30/16_3/16_29/16_28/16_27/16_26/16_25/16_24/16_23/16_22/16_21/16_20/16_2/16_19/16_17/16_16/16_14/16_13/16_12/16_11/16_10/16_1/15_97/15_96/15_95/15_93/15_92/15_91/15_90/15_9/15_87/15_85/15_83/15_82/15_81/15_8/15_79/15_74/15_72/15_71/15_7/15_67/15_6/15_59/15_56/15_55/15_52/15_50/15_5/15_49/15_46/15_44/15_42/15_41/15_40/15_4/15_38/15_36/15_35/15_34/15_33/15_32/15_31/15_30/15_3/15_29/15_28/15_27/15_26/15_25/15_24/15_23/15_22/15_21/15_20/15_2/15_19/15_17/15_16/15_14/15_13/15_12/15_11/15_10/15_1/14_98/14_97/14_95/14_94/14_93/14_92/14_91/14_90/14_9/14_87/14_85/14_83/14_82/14_81/14_80/14_8/14_79/14_74/14_72/14_71/14_7/14_67/14_60/14_6/14_59/14_58/14_56/14_55/14_52/14_50/14_5/14_49/14_46/14_44/14_42/14_41/14_40/14_4/14_38/14_36/14_35/14_34/14_33/14_32/14_31/14_30/14_3/14_29/14_28/14_27/14_26/14_25/14_24/14_23/14_22/14_21/14_20/14_2/14_19/14_17/14_16/14_14/14_13/14_12/14_11/14_10/14_1/13_98/13_97/13_96/13_95/13_94/13_93/13_92/13_91/13_90/13_9/13_87/13_85/13_83/13_82/13_81/13_80/13_8/13_79/13_74/13_72/13_71/13_7/13_67/13_60/13_6/13_59/13_58/13_56/13_55/13_54/13_52/13_50/13_5/13_49/13_46/13_44/13_42/13_41/13_40/13_4/13_38/13_37/13_36/13_35/13_34/13_33/13_32/13_31/13_30/13_3/13_29/13_28/13_27/13_26/13_25/13_24/13_23/13_22/13_21/13_20/13_2/13_19/13_17/13_16/13_14/13_13/13_12/13_11/13_10/13_1/12_98/12_97/12_95/12_93/12_92/12_91/12_90/12_9/12_87/12_85/12_83/12_82/12_81/12_80/12_8/12_79/12_74/12_72/12_71/12_7/12_67/12_60/12_6/12_59/12_56/12_55/12_52/12_5/12_46/12_44/12_42/12_41/12_40/12_4/12_38/12_36/12_35/12_34/12_33/12_32/12_31/12_30/12_3/12_29/12_28/12_27/12_26/12_25/12_24/12_23/12_22/12_21/12_20/12_2/12_19/12_17/12_16/12_14/12_13/12_12/12_11/12_10/12_1/11_98/11_97/11_96/11_95/11_94/11_93/11_92/11_91/11_90/11_9/11_87/11_85/11_83/11_82/11_81/11_80/11_8/11_79/11_74/11_72/11_71/11_7/11_67/11_6/11_59/11_58/11_56/11_55/11_52/11_5/11_49/11_46/11_44/11_42/11_41/11_40/11_4/11_38/11_37/11_36/11_35/11_34/11_33/11_32/11_31/11_30/11_3/11_29/11_28/11_27/11_26/11_25/11_24/11_23/11_22/11_21/11_20/11_2/11_17/11_16/11_14/11_13/11_12/11_11/11_10/11_1/10_97/10_96/10_95/10_93/10_92/10_91/10_90/10_9/10_87/10_85/10_83/10_82/10_81/10_80/10_8/10_79/10_74/10_72/10_71/10_7/10_67/10_60/10_6/10_59/10_58/10_56/10_55/10_52/10_50/10_5/10_49/10_48/10_46/10_44/10_42/10_41/10_40/10_4/10_38/10_37/10_36/10_35/10_34/10_33/10_32/10_31/10_30/10_3/10_29/10_28/10_27/10_26/10_25/10_24/10_23/10_22/10_21/10_20/10_2/10_19/10_17/10_16/10_14/10_13/10_12/10_11/10_10/10_1"

When you run the flow from a scenario, then you can use the variable name as such ${store_department_combinations}. That is what is included in the existing scenario.

The simplest way is to rebuild the flow thanks to the scenario that is included in the project export.

To practice partitioning in general, you can read this doc:  https://doc.dataiku.com/dss/latest/partitions/index.html

Hope it helps,

Alex
