### ISSUE TITLE
[Lime Plugin] No Recipie

### ISSUE THREAD

**Issue by rymoore** [dataiku/dataiku-contrib#141]
Hi - I've followed the instructions for installing the LIME plugin, but when I select either a prediction model or dataset, I don't see any available "Plugin Recipe" for LIME. I do see it as installed in the Administrative plugin list. What might be the issue?

**Comment by du-phan** [comment]
Hello, 
The recipe is unfortunately not selectable from model or dataset. To use the plugin, from the flow you will need to click on the `+RECIPE` box (on the top right of the flow), then choose the `LIME` plugin from the dropdown and the the recipe.

**Comment by rymoore** [comment]
Got it - thank you! May be helpful to add to the README :)
