### ISSUE TITLE
Broken link to 'Get US Census Block' plugin documentation

### ISSUE THREAD

**Issue by seanangio** [dataiku/dataiku-contrib#146]
Hi @ngakrelidz , it seems the link to the documentation when using the Get US Census block plugin is broken. The existing link is: https://www.dataiku.com/dss/plugins/info/get-us-census-block.html

I think it should be: https://www.dataiku.com/dss/plugins/info/get-us-block.html

<img width="1277" alt="census_block" src="https://user-images.githubusercontent.com/28539853/63958477-6875e380-ca58-11e9-9bbe-3519ac726e53.png">

Thanks,

**Comment by du-phan** [comment]
Updated here https://github.com/dataiku/dataiku-contrib/commit/269113d98be5ccd3974ebe888557b7ab517c6228
