### ISSUE TITLE
google sheets plugin:  Please do not store the service account credentials inside the GIT repo...

### ISSUE THREAD

**Issue by pon-sander** [dataiku/dataiku-contrib#280]
I just found out that by making a google sheet connection from DSS the provided service account credentials  are stored in version controle and then synced to the remote repo.

please create a simulare option as with the Google drive plugin to store the credentials with the plugin so credentials dont leak into the GIT repo.

**Comment by alexbourret** [comment]
Hi @pon-sander 
The plugin has just been updated and can now use presets as well as Google SSO. You can upgrade to v1.2.0 directly from the plugin store, and the repository for the plugin is now located [here](https://github.com/dataiku/dss-plugin-googlesheets/).
