### ISSUE TITLE
Sendmail plugin uses US-Ascii encoding for body text

### ISSUE THREAD

**Issue by andreasschmidtjensen** [dataiku/dataiku-contrib#69]
The Sendmail plugin uses MIMEText, which uses us-ascii as default encoding. This means only a limited set of characters can be used in the email. It can be quite easily fixed by specifying utf-8 as encoding as seen in this commit:

https://github.com/andreasschmidtjensen/dataiku-contrib/commit/57ef80c30df47b3a3407b5a89120551aed6d9724

However, you may want some possibility to specify the encoding in the configuration? Changing the encoding could lead to some backward compatibility issues...

**Comment by ThmsLa** [comment]
Thanks for your input @andreasschmidtjensen !
I'll update the plugin accordingly. Don't hesitate to send us a pull request next time 🙂
