### ISSUE TITLE
Text summarize plugin : MUS integration

### ISSUE THREAD

**Issue by duckie** [dataiku/dataiku-contrib#82]
The plugin tries to download some files in MUS but downlaods in the home of the users, which can lead to issues:
- If users dont have a home on the linux box (which is often likely)
- Would bloat the disk with multiple useless copies of the same download

**Comment by duckie** [comment]
See: https://github.com/dataiku/dataiku-contrib/blob/f9ede5e356524d59cc2da6098ec6b0517e905fcd/text-summarization/custom-recipes/text-summarization-compute/recipe.py#L15

**Comment by du-phan** [comment]
fixed in #177
