### ISSUE TITLE
Audits a dataset plugin: Fails on SQL tables

### ISSUE THREAD

**Issue by RedaAffane** [dataiku/dataiku-contrib#97]
An error occurs when running this plugin on any SQL datatset. The error is the following:
**_ERROR: relation "${projectKey}_DATASET_NAME" does not exist_** 

My understanding is that, when passed through the SQLExecutor2 python API, the variable ${projectKey} doesn't get substituted with the correct value.

**Comment by cstenac** [comment]
Duplicate of #52
