### ISSUE TITLE
[Named Entity Recognition] Better Handling of Input Sentences

### ISSUE THREAD

**Issue by dsleo** [dataiku/dataiku-contrib#99]
This plugin is soooo [dirty](https://github.com/dataiku/dataiku-contrib/blob/master/named-entity-recognition/custom-recipes/named-entity-recognition-extract/recipe.py#L70L90), need to clean up the last fixes.  
In particular:
1. [handle empty sequence separately](https://github.com/dataiku/dataiku-contrib/blob/master/named-entity-recognition/custom-recipes/named-entity-recognition-extract/recipe.py#L71),  
2. do a proper chunk writing (at the moment, this is doing thing in memory, silly). For that need to set up the schema upfront (see [here](https://github.com/dataiku/dataiku-contrib/blob/master/named-entity-recognition/custom-recipes/named-entity-recognition-extract/recipe.py#L80)).

**Comment by du-phan** [comment]
For chunk writing, an example is [here](https://github.com/dataiku/dku-contrib-private/blob/aws-machine-learning/aws-machine-learning/custom-recipes/text-analytics-sentiment-analysis/recipe.py#L60)
